# Generated by Django 5.2.11 on 2026-04-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0002_adminprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("verified", "Verified Document"),
                    ("rejected", "Rejected Document"),
                    ("incomplete", "Marked Incomplete"),
                    ("resubmit", "Requested Resubmission"),
                    ("note", "Added Note"),
                    ("comment", "Added Comment"),
                    ("profile_updated", "Updated Profile"),
                    ("photo_updated", "Changed Profile Photo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adminactivitylog",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="admin_app.application",
            ),
        ),
    ]
