# Generated by Django 5.2.11 on 2026-04-19 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_alter_adminactivitylog_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive updates via email"
                    ),
                ),
                (
                    "new_application_alerts",
                    models.BooleanField(
                        default=True, help_text="Alert when new apps are submitted"
                    ),
                ),
                (
                    "deadline_reminders",
                    models.BooleanField(
                        default=False, help_text="Get reminded before submission close"
                    ),
                ),
                (
                    "document_status_changes",
                    models.BooleanField(
                        default=True, help_text="Notify when docs are verified/rejected"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Notification Preference",
                "verbose_name_plural": "Admin Notification Preferences",
            },
        ),
    ]
