# Generated by Django 5.2.11 on 2026-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_adminnotificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="submission_deadline",
            field=models.DateField(
                blank=True, help_text="Document submission deadline", null=True
            ),
        ),
        migrations.DeleteModel(
            name="AdminNotificationPreference",
        ),
    ]
