# Generated by Django 6.0.3 on 2026-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0005_application_submission_deadline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMSSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admissions_open", models.BooleanField(default=True)),
                ("show_announcement", models.BooleanField(default=True)),
                (
                    "announcement_text",
                    models.CharField(
                        default="Admissions are now open for AY 2025–2026.",
                        max_length=300,
                    ),
                ),
                (
                    "hero_tagline",
                    models.TextField(
                        blank=True,
                        default="Advance your professional journey. Our Master's programs are designed for the next generation of academic and industry leaders.",
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CMS Settings",
            },
        ),
        migrations.AlterField(
            model_name="adminactivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("verified", "Verified Document"),
                    ("rejected", "Rejected Document"),
                    ("incomplete", "Marked Incomplete"),
                    ("resubmit", "Requested Resubmission"),
                    ("note", "Added Note"),
                    ("comment", "Added Comment"),
                    ("profile_updated", "Updated Profile"),
                    ("photo_updated", "Changed Profile Photo"),
                    ("cms_updated", "Updated CMS Settings"),
                ],
                max_length=20,
            ),
        ),
    ]
