# Generated by Django 6.0.3 on 2026-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_cmssettings_alter_adminactivitylog_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmssettings",
            name="announcement_text",
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="announcements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of announcements: [{text, duration}]",
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="programs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of programs: [{name, degree, description, visible}]",
            ),
        ),
    ]
