# Generated by Django 6.0.3 on 2026-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0008_cmssettings_downloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="curriculum",
            field=models.CharField(
                blank=True, help_text="e.g. MIT 2023", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="semester",
            field=models.CharField(
                blank=True, help_text="e.g. 1st Semester", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="year_admitted",
            field=models.CharField(
                blank=True, help_text="e.g. 2025–2026", max_length=20
            ),
        ),
    ]
