# Generated by Django 6.0.3 on 2026-04-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0010_student_requirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Associate Professor, Instructor",
                        max_length=255,
                    ),
                ),
                (
                    "specializations",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of specializations"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="faculty/"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in the faculty list"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculty",
                "ordering": ["order", "last_name"],
            },
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_accreditor",
            field=models.CharField(
                blank=True,
                default="Commission on Higher Education (CHED), Republic of the Philippines",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_copc_number",
            field=models.CharField(
                blank=True,
                default="017, Series of 2019 – issued August 28, 2019",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_curriculum",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Program curriculum structure with course groups",
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_degree",
            field=models.CharField(blank=True, default="MIT", max_length=255),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_description",
            field=models.TextField(
                blank=True, help_text="Main description of the program"
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_effective_year",
            field=models.CharField(blank=True, default="2019–2020", max_length=50),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_institution",
            field=models.CharField(
                blank=True,
                default="Western Mindanao State University, Zamboanga City",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_name",
            field=models.CharField(
                blank=True, default="Master in Information Technology", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_objectives",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of program objectives: [{title, description}]",
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_outcomes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of learning outcomes: [{number, title, description}]",
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_stats",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Program statistics: [{stat_label, stat_value}]",
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_tagline",
            field=models.TextField(
                blank=True,
                default="Preparing professionals for the industrial practice of systems integration, administration, planning, implementation, and the maintenance of complex technology ecosystems.",
            ),
        ),
        migrations.AddField(
            model_name="cmssettings",
            name="program_title",
            field=models.CharField(
                blank=True, default="Master in Information Technology", max_length=255
            ),
        ),
    ]
