# Generated by Django 6.0.3 on 2026-05-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0011_faculty_cmssettings_program_accreditor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="curriculum_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured curriculum data including courses, units, prerequisites, and level distribution",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="program_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("masters", "Master's Degree"),
                    ("doctoral", "Doctoral Degree"),
                    ("certificate", "Certificate Program"),
                ],
                help_text="Program level (Masters, Doctoral, etc.)",
                max_length=50,
            ),
        ),
    ]
