# Generated by Django 5.2.11 on 2026-05-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_application_curriculum_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssettings',
            name='hero_badge',
            field=models.CharField(blank=True, default='Graduate School · Information Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='hero_heading1',
            field=models.CharField(blank=True, default='The University', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='hero_heading2',
            field=models.CharField(blank=True, default='of Choice', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='nav_subtitle',
            field=models.CharField(blank=True, default='MIT · Graduate School Admissions', max_length=255),
        ),
        migrations.AlterField(
            model_name='cmssettings',
            name='hero_tagline',
            field=models.TextField(blank=True, default='Advance your professional journey with the Master of Information Technology program at WMSU Graduate School.'),
        ),
    ]
