# Generated by Django 5.2.11 on 2026-05-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_cmssettings_hero_badge_cmssettings_hero_heading1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssettings',
            name='admission_requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of admission requirements: [{number, title, description}]'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='calendar_events',
            field=models.JSONField(blank=True, default=list, help_text='List of calendar events: [{id, month, day, title, type, tag, time, venue, audience, desc}]'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='contact_address',
            field=models.CharField(blank=True, default='WMSU Main Campus, Normal Road, Baliwasan, Zamboanga City', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='admissions@wmsu.edu.ph', max_length=254),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='contact_facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='contact_hours',
            field=models.CharField(blank=True, default='Mon–Fri, 8AM–5PM', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='(062) 991-1771', max_length=50),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='event_slides',
            field=models.JSONField(blank=True, default=list, help_text='List of event slides for carousel: [{title, date, day_label, time, venue, description, image_url, audience, featured}]'),
        ),
    ]
