# Generated by Django 5.2.11 on 2026-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_cmssettings_admission_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssettings',
            name='app_stat_label1',
            field=models.CharField(blank=True, default='Program', help_text='Label for the first stat badge shown in the application window card', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='app_stat_label2',
            field=models.CharField(blank=True, default='Enrollment', help_text='Label for the second stat badge shown in the application window card', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='app_stat_val1',
            field=models.CharField(blank=True, default='MIT', help_text='First stat badge value shown in the application window card', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='app_stat_val2',
            field=models.CharField(blank=True, default='4', help_text='Second stat badge value shown in the application window card', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='app_window_ay',
            field=models.CharField(blank=True, default='Academic Year 2026–2027', help_text='Academic year label shown on the application window card', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='app_window_deadline_year',
            field=models.CharField(blank=True, default='2026', help_text='Deadline year text shown on the application window card', max_length=10),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='app_window_enrollment',
            field=models.CharField(blank=True, default='July', help_text='Enrollment month label shown on the application window card', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='app_window_enrollment_year',
            field=models.CharField(blank=True, default='2026', help_text='Enrollment year text shown on the application window card', max_length=10),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='cta_heading',
            field=models.CharField(blank=True, default='Ready to take the next step?', help_text='Call-to-action heading displayed in the application window card', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='cta_sublabel',
            field=models.CharField(blank=True, default='Applications open for AY 2026–2027', help_text='Call-to-action sublabel displayed in the application window card', max_length=255),
        ),
    ]
