# Generated by Django 5.2.11 on 2026-05-06 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0016_schoolyear"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProspectusSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(default="Semester", max_length=120)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Prospectus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "program_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional program name this prospectus applies to",
                        max_length=255,
                    ),
                ),
                (
                    "program_code",
                    models.CharField(
                        blank=True, help_text="Optional program code", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prospectuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProspectusSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(blank=True, max_length=64)),
                ("title", models.CharField(max_length=512)),
                ("prereq", models.CharField(blank=True, max_length=255)),
                ("lec", models.PositiveSmallIntegerField(default=0)),
                ("lab", models.PositiveSmallIntegerField(default=0)),
                ("total", models.PositiveSmallIntegerField(default=0)),
                ("grade", models.CharField(blank=True, max_length=16)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="admin_app.prospectussemester",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProspectusYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(default="Year", max_length=120)),
                (
                    "prospectus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="years",
                        to="admin_app.prospectus",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("prospectus", "order")},
            },
        ),
        migrations.AddField(
            model_name="prospectussemester",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="admin_app.prospectusyear",
            ),
        ),
        migrations.CreateModel(
            name="ProspectusAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(
                        blank=True,
                        help_text="Program name this prospectus is assigned to",
                        max_length=255,
                    ),
                ),
                (
                    "program_code",
                    models.CharField(
                        blank=True, help_text="Optional program code", max_length=64
                    ),
                ),
                (
                    "intake_year",
                    models.CharField(
                        blank=True, help_text="e.g., 2019-2020", max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prospectus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="admin_app.prospectus",
                    ),
                ),
            ],
            options={
                "unique_together": {("program_name", "intake_year")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="prospectussemester",
            unique_together={("year", "order")},
        ),
    ]
