# Generated by Django 5.2.11 on 2026-05-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_schoolyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssettings',
            name='about_courses',
            field=models.JSONField(blank=True, default=list, help_text='List of courses: [{code, name, units, description}]'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_hero_badge',
            field=models.CharField(blank=True, default='CHED Compliant · Effective S.Y. 2019–2020', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_hero_eyebrow',
            field=models.CharField(blank=True, default='Western Mindanao State University · College of Computing Studies', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_hero_tagline',
            field=models.TextField(blank=True, default='Preparing professionals for systems integration, administration, planning, implementation, and maintenance of complex technology ecosystems.'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_hero_title',
            field=models.CharField(blank=True, default='Master in', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_hero_title_italic',
            field=models.CharField(blank=True, default='Information Technology', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of program objectives: [{title, description}]'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_outcomes',
            field=models.JSONField(blank=True, default=list, help_text='List of learning outcomes: [{number, title, description}]'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_overview_image',
            field=models.ImageField(blank=True, help_text='Image shown in the right column of the About overview section', null=True, upload_to='cms/about/'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_overview_text',
            field=models.TextField(blank=True, default='The Master in Information Technology (MIT) at Western Mindanao State University emphasizes the acquisition of advanced concepts and technologies, preparing graduates for the industrial practice of systems integration, systems administration, systems planning, and systems implementation — maintaining the integrity and proper functionality of complex systems.'),
        ),
    ]
