# Generated by Django 5.2.11 on 2026-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_cmssettings_about_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssettings',
            name='about_info_institution',
            field=models.TextField(blank=True, default='Western Mindanao State University'),
        ),
    ]
