# Generated by Django 5.2.11 on 2026-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_cmssettings_about_info_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssettings',
            name='about_ched_desc',
            field=models.TextField(blank=True, default='Complies with CHED Resolution No. 405-2019 and Republic Act No. 7722 (Higher Education Act of 1994).'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_ched_heading',
            field=models.CharField(blank=True, default='CHED Certified Program', max_length=255),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_info_accred',
            field=models.TextField(blank=True, default='Commission on Higher Education (CHED), Philippines'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_info_ay',
            field=models.CharField(blank=True, default='2019–2020', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_info_copc',
            field=models.TextField(blank=True, default='017, Series of 2019 — August 28, 2019'),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_stat1_lbl',
            field=models.CharField(blank=True, default='Total Units', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_stat1_val',
            field=models.CharField(blank=True, default='39', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_stat2_lbl',
            field=models.CharField(blank=True, default='Years Duration', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_stat2_val',
            field=models.CharField(blank=True, default='2', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_stat3_lbl',
            field=models.CharField(blank=True, default='Core Course Units', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_stat3_val',
            field=models.CharField(blank=True, default='12', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_stat4_lbl',
            field=models.CharField(blank=True, default='Specialization Units', max_length=100),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='about_stat4_val',
            field=models.CharField(blank=True, default='21', max_length=100),
        ),
    ]
