# Generated by Django 5.2.11 on 2026-05-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_cmssettings_about_ched_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssettings',
            name='about_faculty',
            field=models.JSONField(blank=True, default=list, help_text='List of faculty members: [{name, title, bio, tags}]'),
        ),
    ]
