# Generated by Django 5.2.11 on 2026-05-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0018_program"),
        ("admin_app", "0019_cmssettings_about_ched_desc_and_more"),
    ]

    operations = []
