# Generated by Django 5.2.11 on 2026-05-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_cmssettings_about_faculty'),
        ('admin_app', '0020_merge_20260507_0758'),
    ]

    operations = [
    ]
