# Generated by Django 5.2.11 on 2026-05-14 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_adminprofile_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('verified', 'Verified Document'), ('rejected', 'Rejected Document'), ('incomplete', 'Marked Incomplete'), ('resubmit', 'Requested Resubmission'), ('note', 'Added Note'), ('comment', 'Added Comment'), ('profile_updated', 'Updated Profile'), ('photo_updated', 'Changed Profile Photo'), ('cms_updated', 'Updated CMS Settings'), ('messaging', 'Sent Message')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('cor_upload', 'COR Uploaded'), ('grade_upload', 'Grade Screenshot Uploaded'), ('requirement_submitted', 'Requirement Submitted'), ('document_upload', 'Document Uploaded')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
