# Generated by Django 5.2.11 on 2026-05-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_add_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssettings',
            name='enrollment_end_date',
            field=models.DateField(blank=True, help_text='Enrollment period end date.', null=True),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='enrollment_start_date',
            field=models.DateField(blank=True, help_text='Enrollment period start date. If set, Apply Now is only active between start and end.', null=True),
        ),
        migrations.AddField(
            model_name='cmssettings',
            name='hero_bg_image_url',
            field=models.CharField(blank=True, help_text='URL of the uploaded hero section background image', max_length=500),
        ),
    ]
