# Generated by Django 5.2.11 on 2026-06-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_add_cms_hero_enrollment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('cor_upload', 'COR Uploaded'), ('grade_upload', 'Grade Screenshot Uploaded'), ('requirement_submitted', 'Requirement Submitted'), ('document_upload', 'Document Uploaded'), ('enrollment_submitted', 'Enrollment Application Submitted')], max_length=40),
        ),
    ]
