# Generated by Django 5.2.11 on 2026-06-23 09:29

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Program = apps.get_model('admin_app', 'Program')
    used_slugs = set()
    for program in Program.objects.all():
        base_slug = slugify(program.name) or f'program-{program.pk}'
        slug = base_slug
        counter = 1
        while slug in used_slugs:
            slug = f'{base_slug}-{counter}'
            counter += 1
        used_slugs.add(slug)
        program.slug = slug
        program.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0028_alter_adminnotification_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prospectus",
            name="program_code",
        ),
        migrations.RemoveField(
            model_name="prospectus",
            name="program_name",
        ),
        # Drop any partial state left by previous failed migration attempts.
        # DROP COLUMN CASCADE also removes all indexes/constraints on the column.
        migrations.RunSQL(
            sql="ALTER TABLE admin_app_program DROP COLUMN IF EXISTS slug",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # db_index=False prevents AddField from queuing a _like deferred index;
        # AlterField below handles all final indexes exactly once.
        migrations.AddField(
            model_name="program",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, default='', db_index=False),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="program",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="prospectus",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prospectuses",
                to="admin_app.program",
            ),
        ),
        migrations.DeleteModel(
            name="ProspectusAssignment",
        ),
    ]
