# Generated by Django 5.2.11 on 2026-06-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0028_alter_adminnotification_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prospectus",
            name="program_code",
        ),
        migrations.RemoveField(
            model_name="prospectus",
            name="program_name",
        ),
        migrations.AddField(
            model_name="program",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="prospectus",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prospectuses",
                to="admin_app.program",
            ),
        ),
        migrations.DeleteModel(
            name="ProspectusAssignment",
        ),
    ]
