# Generated by Django 5.2.11 on 2026-06-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0029_remove_prospectus_program_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospectussubject",
            name="is_core",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prospectussubject",
            name="is_specialization",
            field=models.BooleanField(default=False),
        ),
    ]
