# Generated by Django 5.2.11 on 2026-03-26 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('deans_recommendation', "Dean's Recommendation"), ('tor', 'Transcript of Records'), ('honorable_dismissal', 'Honorable Dismissal'), ('psa', 'PSA (Live Birth)'), ('gsat', 'GSAT (Graduate School Admission Test)')], max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=64)),
                ('civil_status', models.CharField(max_length=64)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('religion_other', models.CharField(blank=True, max_length=255)),
                ('ethnicity', models.CharField(max_length=255)),
                ('ethnicity_other', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('nationality_other', models.CharField(blank=True, max_length=255)),
                ('disability', models.CharField(max_length=255)),
                ('disability_other', models.CharField(blank=True, max_length=255)),
                ('permanent_address', models.CharField(max_length=500)),
                ('current_address', models.CharField(blank=True, max_length=500)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('name_of_parent', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=128)),
                ('parent_income', models.CharField(max_length=128)),
                ('name_of_spouse', models.CharField(blank=True, max_length=255)),
                ('spouse_contact_number', models.CharField(blank=True, max_length=50)),
                ('spouse_income', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('form_version', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_employed', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('monthly_income', models.CharField(blank=True, max_length=50)),
                ('employment_status', models.CharField(blank=True, max_length=64)),
                ('employment_status_other', models.CharField(blank=True, max_length=255)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('employer_address', models.CharField(blank=True, max_length=500)),
                ('employer_contact', models.CharField(blank=True, max_length=50)),
                ('employer_classification', models.CharField(blank=True, max_length=64)),
                ('employer_classification_other', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('elementary', 'Elementary'), ('secondary', 'Secondary'), ('college', 'College'), ('graduate', 'Graduate Studies')], max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('degree_course', models.CharField(blank=True, max_length=255)),
                ('year_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('scholarship', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'level')},
            },
        ),
    ]
