# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_document_personaldetails_privacyconsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
