# Generated by Django 5.2.11 on 2026-05-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students_app", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(max_length=255),
        ),
    ]
