# Generated by Django 5.2.11 on 2026-05-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0005_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('deans_recommendation', "Dean's Recommendation"), ('tor', 'Transcript of Records'), ('honorable_dismissal', 'Honorable Dismissal'), ('psa', 'PSA (Live Birth)'), ('gsat', 'GSAT (Graduate School Admission Test)')], max_length=255),
        ),
    ]
