# Generated by Django 5.2.11 on 2026-05-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students_app", "0005_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalbackground",
            name="mit_curriculum",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
