# Generated by Django 5.2.11 on 2026-05-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students_app", "0006_alter_document_document_type"),
        ("students_app", "0006_educationalbackground_mit_curriculum"),
    ]

    operations = []
