# Generated by Cursor on 2026-05-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students_app", "0008_alter_document_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CORSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year_level", models.CharField(blank=True, max_length=64)),
                ("semester", models.CharField(max_length=64)),
                ("school_year", models.CharField(max_length=64)),
                ("cor_file", models.FileField(upload_to="cor/")),
                ("status", models.CharField(choices=[("Pending", "Pending"), ("Verified", "Verified"), ("Rejected", "Rejected")], default="Pending", max_length=16)),
                ("admin_remarks", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cor_submissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "unique_together": {("user", "year_level", "semester", "school_year")},
            },
        ),
        migrations.CreateModel(
            name="GradeSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("semester", models.CharField(max_length=64)),
                ("school_year", models.CharField(max_length=64)),
                ("gpa", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("screenshot", models.FileField(blank=True, null=True, upload_to="grades/")),
                ("status", models.CharField(choices=[("Pending", "Pending"), ("Acknowledged", "Acknowledged"), ("Flagged", "Flagged")], default="Pending", max_length=16)),
                ("admin_remarks", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grade_submissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("units", models.PositiveSmallIntegerField(default=0)),
                ("grade", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="students_app.gradesubmission")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]

