# Generated by Django 5.2.11 on 2026-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0011_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeentry',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='semester_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='year_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gradesubmission',
            name='curriculum_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gradeentry',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='gradesubmission',
            name='school_year',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='gradesubmission',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='grade_submissions/'),
        ),
        migrations.AlterField(
            model_name='gradesubmission',
            name='semester',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gradesubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Flagged', 'Flagged')], default='Pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='gradeentry',
            unique_together={('submission', 'year_label', 'semester_label', 'code')},
        ),
    ]
